### ISSUE TITLE
Overlapping figures in output

### ISSUE THREAD

**Issue by sam687** [jpdeleon/tql#4]
I have been using tql successfully but the figures generated are overlapped for every "ticid". Is there any solution?
![download](https://user-images.githubusercontent.com/14346325/190071708-9901482e-e5f5-4c62-827c-5107f452587a.png)

**Comment by jpdeleon** [comment]
That looks strange. It's probably due to your screen's current resolution. Are you running locally in your machine, remote server, or via google colab? 

One solution is to use the `-s` flag (if you ran it using the tql script) to save the output figure first then view it later.

**Comment by sam687** [comment]
Locally in my machine. Yes the resolution of the monitor is low. Ok I will check by saving the figures. Thanks very much.

**Comment by jpdeleon** [comment]
OK! Please close this issue if fixed.

**Comment by sam687** [comment]
The figures overlapped in 2nd run of the code without restarting the notebook kernel. It is working after restarting the kernel. So every time we run it, just restarting the kernel would solve it.
